// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: map-service/v1/map.proto

package mapv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectType int32

const (
	ObjectType_OBJECT_TYPE_UNSPECIFIED ObjectType = 0
	ObjectType_PARK                    ObjectType = 1
	ObjectType_DOG_PARK                ObjectType = 2
	ObjectType_DOG_BEACH               ObjectType = 3
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "OBJECT_TYPE_UNSPECIFIED",
		1: "PARK",
		2: "DOG_PARK",
		3: "DOG_BEACH",
	}
	ObjectType_value = map[string]int32{
		"OBJECT_TYPE_UNSPECIFIED": 0,
		"PARK":                    1,
		"DOG_PARK":                2,
		"DOG_BEACH":               3,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_map_service_v1_map_proto_enumTypes[0].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_map_service_v1_map_proto_enumTypes[0]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_map_service_v1_map_proto_rawDescGZIP(), []int{0}
}

type PresenceAction int32

const (
	PresenceAction_PRESENCE_ACTION_UNSPECIFIED PresenceAction = 0
	PresenceAction_VISITING                    PresenceAction = 1
	PresenceAction_NOT_VISITING                PresenceAction = 2
)

// Enum value maps for PresenceAction.
var (
	PresenceAction_name = map[int32]string{
		0: "PRESENCE_ACTION_UNSPECIFIED",
		1: "VISITING",
		2: "NOT_VISITING",
	}
	PresenceAction_value = map[string]int32{
		"PRESENCE_ACTION_UNSPECIFIED": 0,
		"VISITING":                    1,
		"NOT_VISITING":                2,
	}
)

func (x PresenceAction) Enum() *PresenceAction {
	p := new(PresenceAction)
	*p = x
	return p
}

func (x PresenceAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceAction) Descriptor() protoreflect.EnumDescriptor {
	return file_map_service_v1_map_proto_enumTypes[1].Descriptor()
}

func (PresenceAction) Type() protoreflect.EnumType {
	return &file_map_service_v1_map_proto_enumTypes[1]
}

func (x PresenceAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PresenceAction.Descriptor instead.
func (PresenceAction) EnumDescriptor() ([]byte, []int) {
	return file_map_service_v1_map_proto_rawDescGZIP(), []int{1}
}

// MapObject is the client-facing shape. It carries the privacy-filtered presence
// view: a count for everyone and the caller's friends who are here by name (id).
type MapObject struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ObjectType   ObjectType             `protobuf:"varint,2,opt,name=object_type,json=objectType,proto3,enum=map.v1.ObjectType" json:"object_type,omitempty"`
	Longitude    float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude     float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	VisitorCount uint32                 `protobuf:"varint,5,opt,name=visitor_count,json=visitorCount,proto3" json:"visitor_count,omitempty"`
	// friend_ids_here = SINTER(object:{id}:visitors, friends:{caller}).
	// Only the caller's friends appear; never the raw visitor set.
	FriendIdsHere []string `protobuf:"bytes,6,rep,name=friend_ids_here,json=friendIdsHere,proto3" json:"friend_ids_here,omitempty"`
	// viewer_visiting is true when the CALLER currently holds presence in this
	// object (derived from presence:{caller}). Lets the client render the correct
	// toggle state and avoid re-marking after a page refresh.
	ViewerVisiting bool `protobuf:"varint,7,opt,name=viewer_visiting,json=viewerVisiting,proto3" json:"viewer_visiting,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MapObject) Reset() {
	*x = MapObject{}
	mi := &file_map_service_v1_map_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapObject) ProtoMessage() {}

func (x *MapObject) ProtoReflect() protoreflect.Message {
	mi := &file_map_service_v1_map_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapObject.ProtoReflect.Descriptor instead.
func (*MapObject) Descriptor() ([]byte, []int) {
	return file_map_service_v1_map_proto_rawDescGZIP(), []int{0}
}

func (x *MapObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MapObject) GetObjectType() ObjectType {
	if x != nil {
		return x.ObjectType
	}
	return ObjectType_OBJECT_TYPE_UNSPECIFIED
}

func (x *MapObject) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *MapObject) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *MapObject) GetVisitorCount() uint32 {
	if x != nil {
		return x.VisitorCount
	}
	return 0
}

func (x *MapObject) GetFriendIdsHere() []string {
	if x != nil {
		return x.FriendIdsHere
	}
	return nil
}

func (x *MapObject) GetViewerVisiting() bool {
	if x != nil {
		return x.ViewerVisiting
	}
	return false
}

type LoadMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMapRequest) Reset() {
	*x = LoadMapRequest{}
	mi := &file_map_service_v1_map_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMapRequest) ProtoMessage() {}

func (x *LoadMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_service_v1_map_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMapRequest.ProtoReflect.Descriptor instead.
func (*LoadMapRequest) Descriptor() ([]byte, []int) {
	return file_map_service_v1_map_proto_rawDescGZIP(), []int{1}
}

func (x *LoadMapRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LoadMapRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type LoadMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Objects       []*MapObject           `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMapResponse) Reset() {
	*x = LoadMapResponse{}
	mi := &file_map_service_v1_map_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMapResponse) ProtoMessage() {}

func (x *LoadMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_service_v1_map_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMapResponse.ProtoReflect.Descriptor instead.
func (*LoadMapResponse) Descriptor() ([]byte, []int) {
	return file_map_service_v1_map_proto_rawDescGZIP(), []int{2}
}

func (x *LoadMapResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoadMapResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoadMapResponse) GetObjects() []*MapObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

type GetMapObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapObjectRequest) Reset() {
	*x = GetMapObjectRequest{}
	mi := &file_map_service_v1_map_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapObjectRequest) ProtoMessage() {}

func (x *GetMapObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_service_v1_map_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapObjectRequest.ProtoReflect.Descriptor instead.
func (*GetMapObjectRequest) Descriptor() ([]byte, []int) {
	return file_map_service_v1_map_proto_rawDescGZIP(), []int{3}
}

func (x *GetMapObjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ChangeMapObjectStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        PresenceAction         `protobuf:"varint,2,opt,name=action,proto3,enum=map.v1.PresenceAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMapObjectStatusRequest) Reset() {
	*x = ChangeMapObjectStatusRequest{}
	mi := &file_map_service_v1_map_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMapObjectStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMapObjectStatusRequest) ProtoMessage() {}

func (x *ChangeMapObjectStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_service_v1_map_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMapObjectStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeMapObjectStatusRequest) Descriptor() ([]byte, []int) {
	return file_map_service_v1_map_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeMapObjectStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeMapObjectStatusRequest) GetAction() PresenceAction {
	if x != nil {
		return x.Action
	}
	return PresenceAction_PRESENCE_ACTION_UNSPECIFIED
}

type MapObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Object        *MapObject             `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapObjectResponse) Reset() {
	*x = MapObjectResponse{}
	mi := &file_map_service_v1_map_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapObjectResponse) ProtoMessage() {}

func (x *MapObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_service_v1_map_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapObjectResponse.ProtoReflect.Descriptor instead.
func (*MapObjectResponse) Descriptor() ([]byte, []int) {
	return file_map_service_v1_map_proto_rawDescGZIP(), []int{5}
}

func (x *MapObjectResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MapObjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MapObjectResponse) GetObject() *MapObject {
	if x != nil {
		return x.Object
	}
	return nil
}

var File_map_service_v1_map_proto protoreflect.FileDescriptor

const file_map_service_v1_map_proto_rawDesc = "" +
	"\n" +
	"\x18map-service/v1/map.proto\x12\x06map.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"\x80\x02\n" +
	"\tMapObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\vobject_type\x18\x02 \x01(\x0e2\x12.map.v1.ObjectTypeR\n" +
	"objectType\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12#\n" +
	"\rvisitor_count\x18\x05 \x01(\rR\fvisitorCount\x12&\n" +
	"\x0ffriend_ids_here\x18\x06 \x03(\tR\rfriendIdsHere\x12'\n" +
	"\x0fviewer_visiting\x18\a \x01(\bR\x0eviewerVisiting\"|\n" +
	"\x0eLoadMapRequest\x125\n" +
	"\tlongitude\x18\x01 \x01(\x01B\x17\xfaB\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\tlongitude\x123\n" +
	"\blatitude\x18\x02 \x01(\x01B\x17\xfaB\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\blatitude\"l\n" +
	"\x0fLoadMapResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\aobjects\x18\x03 \x03(\v2\x11.map.v1.MapObjectR\aobjects\"/\n" +
	"\x13GetMapObjectRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"t\n" +
	"\x1cChangeMapObjectStatusRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12:\n" +
	"\x06action\x18\x02 \x01(\x0e2\x16.map.v1.PresenceActionB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x06action\"l\n" +
	"\x11MapObjectResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x06object\x18\x03 \x01(\v2\x11.map.v1.MapObjectR\x06object*P\n" +
	"\n" +
	"ObjectType\x12\x1b\n" +
	"\x17OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04PARK\x10\x01\x12\f\n" +
	"\bDOG_PARK\x10\x02\x12\r\n" +
	"\tDOG_BEACH\x10\x03*Q\n" +
	"\x0ePresenceAction\x12\x1f\n" +
	"\x1bPRESENCE_ACTION_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bVISITING\x10\x01\x12\x10\n" +
	"\fNOT_VISITING\x10\x022\xb9\x02\n" +
	"\n" +
	"MapService\x12S\n" +
	"\aLoadMap\x12\x16.map.v1.LoadMapRequest\x1a\x17.map.v1.LoadMapResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/map/load\x12a\n" +
	"\fGetMapObject\x12\x1b.map.v1.GetMapObjectRequest\x1a\x19.map.v1.MapObjectResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/map/object\x12s\n" +
	"\x15ChangeMapObjectStatus\x12$.map.v1.ChangeMapObjectStatusRequest\x1a\x19.map.v1.MapObjectResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/map/statusB*Z(map-service/pkg/api/map-service/v1;mapv1b\x06proto3"

var (
	file_map_service_v1_map_proto_rawDescOnce sync.Once
	file_map_service_v1_map_proto_rawDescData []byte
)

func file_map_service_v1_map_proto_rawDescGZIP() []byte {
	file_map_service_v1_map_proto_rawDescOnce.Do(func() {
		file_map_service_v1_map_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_map_service_v1_map_proto_rawDesc), len(file_map_service_v1_map_proto_rawDesc)))
	})
	return file_map_service_v1_map_proto_rawDescData
}

var file_map_service_v1_map_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_map_service_v1_map_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_map_service_v1_map_proto_goTypes = []any{
	(ObjectType)(0),                      // 0: map.v1.ObjectType
	(PresenceAction)(0),                  // 1: map.v1.PresenceAction
	(*MapObject)(nil),                    // 2: map.v1.MapObject
	(*LoadMapRequest)(nil),               // 3: map.v1.LoadMapRequest
	(*LoadMapResponse)(nil),              // 4: map.v1.LoadMapResponse
	(*GetMapObjectRequest)(nil),          // 5: map.v1.GetMapObjectRequest
	(*ChangeMapObjectStatusRequest)(nil), // 6: map.v1.ChangeMapObjectStatusRequest
	(*MapObjectResponse)(nil),            // 7: map.v1.MapObjectResponse
}
var file_map_service_v1_map_proto_depIdxs = []int32{
	0, // 0: map.v1.MapObject.object_type:type_name -> map.v1.ObjectType
	2, // 1: map.v1.LoadMapResponse.objects:type_name -> map.v1.MapObject
	1, // 2: map.v1.ChangeMapObjectStatusRequest.action:type_name -> map.v1.PresenceAction
	2, // 3: map.v1.MapObjectResponse.object:type_name -> map.v1.MapObject
	3, // 4: map.v1.MapService.LoadMap:input_type -> map.v1.LoadMapRequest
	5, // 5: map.v1.MapService.GetMapObject:input_type -> map.v1.GetMapObjectRequest
	6, // 6: map.v1.MapService.ChangeMapObjectStatus:input_type -> map.v1.ChangeMapObjectStatusRequest
	4, // 7: map.v1.MapService.LoadMap:output_type -> map.v1.LoadMapResponse
	7, // 8: map.v1.MapService.GetMapObject:output_type -> map.v1.MapObjectResponse
	7, // 9: map.v1.MapService.ChangeMapObjectStatus:output_type -> map.v1.MapObjectResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_map_service_v1_map_proto_init() }
func file_map_service_v1_map_proto_init() {
	if File_map_service_v1_map_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_map_service_v1_map_proto_rawDesc), len(file_map_service_v1_map_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_map_service_v1_map_proto_goTypes,
		DependencyIndexes: file_map_service_v1_map_proto_depIdxs,
		EnumInfos:         file_map_service_v1_map_proto_enumTypes,
		MessageInfos:      file_map_service_v1_map_proto_msgTypes,
	}.Build()
	File_map_service_v1_map_proto = out.File
	file_map_service_v1_map_proto_goTypes = nil
	file_map_service_v1_map_proto_depIdxs = nil
}
