// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: map-service/v1/map.proto

package mapv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MapService_LoadMap_FullMethodName               = "/map.v1.MapService/LoadMap"
	MapService_GetMapObject_FullMethodName          = "/map.v1.MapService/GetMapObject"
	MapService_ChangeMapObjectStatus_FullMethodName = "/map.v1.MapService/ChangeMapObjectStatus"
)

// MapServiceClient is the client API for MapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MapService owns dog-relevant map objects (parks, dog-parks, dog beaches) and
// their ephemeral presence. It applies the DogMap privacy model: visitor_count
// for everyone, friend_ids_here computed for the calling user only. The raw
// visitor id list is NEVER returned to a client.
//
// The acting user id is derived from the opaque session token (header
// `auth_token`), never from the request body. Body ids are only *target* ids.
type MapServiceClient interface {
	// LoadMap returns every map object within 5km of the caller's point
	// (ST_DWithin(location, point, 5000)), each with visitor_count and the
	// caller's friend_ids_here.
	LoadMap(ctx context.Context, in *LoadMapRequest, opts ...grpc.CallOption) (*LoadMapResponse, error)
	// GetMapObject returns a single object with its presence view for the caller.
	GetMapObject(ctx context.Context, in *GetMapObjectRequest, opts ...grpc.CallOption) (*MapObjectResponse, error)
	// ChangeMapObjectStatus marks the caller VISITING or NOT_VISITING the target
	// object and returns the updated object view. No user_id in the body — the
	// acting user is the token owner.
	ChangeMapObjectStatus(ctx context.Context, in *ChangeMapObjectStatusRequest, opts ...grpc.CallOption) (*MapObjectResponse, error)
}

type mapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMapServiceClient(cc grpc.ClientConnInterface) MapServiceClient {
	return &mapServiceClient{cc}
}

func (c *mapServiceClient) LoadMap(ctx context.Context, in *LoadMapRequest, opts ...grpc.CallOption) (*LoadMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadMapResponse)
	err := c.cc.Invoke(ctx, MapService_LoadMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapServiceClient) GetMapObject(ctx context.Context, in *GetMapObjectRequest, opts ...grpc.CallOption) (*MapObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapObjectResponse)
	err := c.cc.Invoke(ctx, MapService_GetMapObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapServiceClient) ChangeMapObjectStatus(ctx context.Context, in *ChangeMapObjectStatusRequest, opts ...grpc.CallOption) (*MapObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapObjectResponse)
	err := c.cc.Invoke(ctx, MapService_ChangeMapObjectStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapServiceServer is the server API for MapService service.
// All implementations must embed UnimplementedMapServiceServer
// for forward compatibility.
//
// MapService owns dog-relevant map objects (parks, dog-parks, dog beaches) and
// their ephemeral presence. It applies the DogMap privacy model: visitor_count
// for everyone, friend_ids_here computed for the calling user only. The raw
// visitor id list is NEVER returned to a client.
//
// The acting user id is derived from the opaque session token (header
// `auth_token`), never from the request body. Body ids are only *target* ids.
type MapServiceServer interface {
	// LoadMap returns every map object within 5km of the caller's point
	// (ST_DWithin(location, point, 5000)), each with visitor_count and the
	// caller's friend_ids_here.
	LoadMap(context.Context, *LoadMapRequest) (*LoadMapResponse, error)
	// GetMapObject returns a single object with its presence view for the caller.
	GetMapObject(context.Context, *GetMapObjectRequest) (*MapObjectResponse, error)
	// ChangeMapObjectStatus marks the caller VISITING or NOT_VISITING the target
	// object and returns the updated object view. No user_id in the body — the
	// acting user is the token owner.
	ChangeMapObjectStatus(context.Context, *ChangeMapObjectStatusRequest) (*MapObjectResponse, error)
	mustEmbedUnimplementedMapServiceServer()
}

// UnimplementedMapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMapServiceServer struct{}

func (UnimplementedMapServiceServer) LoadMap(context.Context, *LoadMapRequest) (*LoadMapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadMap not implemented")
}
func (UnimplementedMapServiceServer) GetMapObject(context.Context, *GetMapObjectRequest) (*MapObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMapObject not implemented")
}
func (UnimplementedMapServiceServer) ChangeMapObjectStatus(context.Context, *ChangeMapObjectStatusRequest) (*MapObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeMapObjectStatus not implemented")
}
func (UnimplementedMapServiceServer) mustEmbedUnimplementedMapServiceServer() {}
func (UnimplementedMapServiceServer) testEmbeddedByValue()                    {}

// UnsafeMapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapServiceServer will
// result in compilation errors.
type UnsafeMapServiceServer interface {
	mustEmbedUnimplementedMapServiceServer()
}

func RegisterMapServiceServer(s grpc.ServiceRegistrar, srv MapServiceServer) {
	// If the following call panics, it indicates UnimplementedMapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MapService_ServiceDesc, srv)
}

func _MapService_LoadMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapServiceServer).LoadMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapService_LoadMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapServiceServer).LoadMap(ctx, req.(*LoadMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapService_GetMapObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMapObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapServiceServer).GetMapObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapService_GetMapObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapServiceServer).GetMapObject(ctx, req.(*GetMapObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapService_ChangeMapObjectStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeMapObjectStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapServiceServer).ChangeMapObjectStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapService_ChangeMapObjectStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapServiceServer).ChangeMapObjectStatus(ctx, req.(*ChangeMapObjectStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MapService_ServiceDesc is the grpc.ServiceDesc for MapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "map.v1.MapService",
	HandlerType: (*MapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadMap",
			Handler:    _MapService_LoadMap_Handler,
		},
		{
			MethodName: "GetMapObject",
			Handler:    _MapService_GetMapObject_Handler,
		},
		{
			MethodName: "ChangeMapObjectStatus",
			Handler:    _MapService_ChangeMapObjectStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "map-service/v1/map.proto",
}
