// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: profiles/v1/profiles.proto

package profilesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfilesService_GetUserInfo_FullMethodName        = "/profiles.v1.ProfilesService/GetUserInfo"
	ProfilesService_FindUserByLogin_FullMethodName    = "/profiles.v1.ProfilesService/FindUserByLogin"
	ProfilesService_EditUser_FullMethodName           = "/profiles.v1.ProfilesService/EditUser"
	ProfilesService_SendFriendRequest_FullMethodName  = "/profiles.v1.ProfilesService/SendFriendRequest"
	ProfilesService_SendFriendResponse_FullMethodName = "/profiles.v1.ProfilesService/SendFriendResponse"
	ProfilesService_ListFriends_FullMethodName        = "/profiles.v1.ProfilesService/ListFriends"
	ProfilesService_RemoveFriend_FullMethodName       = "/profiles.v1.ProfilesService/RemoveFriend"
	ProfilesService_BlockUser_FullMethodName          = "/profiles.v1.ProfilesService/BlockUser"
	ProfilesService_UnblockUser_FullMethodName        = "/profiles.v1.ProfilesService/UnblockUser"
	ProfilesService_CreateProfile_FullMethodName      = "/profiles.v1.ProfilesService/CreateProfile"
)

// ProfilesServiceClient is the client API for ProfilesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Profiles owns user profiles, pets, the friend graph, and blocking. It never
// returns presence itself (Map owns presence) — instead it keeps the
// `friends:{user_id}` Valkey set fresh so Map can do privacy filtering.
//
// Edge RPCs derive the acting user from the opaque session token in the
// `auth_token` header (resolved via Valkey `session:{token}`); body ids are only
// ever *target* ids. CreateProfile is internal (called by Auth over gRPC) and is
// intentionally NOT annotated for the HTTP edge.
type ProfilesServiceClient interface {
	// GetUserInfo returns the target's profile. Full shape (incl. email/phone) to
	// self or friends; reduced shape (no PII) to non-friends.
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	// FindUserByLogin looks up a user by login (case-insensitive; login is citext)
	// for stranger discovery — the frontend's "find a friend by login" search. It
	// ALWAYS returns the reduced (no-PII) shape, even when the looked-up user is
	// already a friend: a discovery endpoint must not be a PII surface, and full
	// details for real friends are available via GetUserInfo. friend_status is
	// still computed so the frontend can render the right button. If no user has
	// that login, the response carries a not-found envelope (code/message), not an
	// error.
	FindUserByLogin(ctx context.Context, in *FindUserByLoginRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	// EditUser updates the *acting user's own* profile (name/surname/phone/pets).
	// No user_id in the body; login/email are not editable here.
	EditUser(ctx context.Context, in *EditUserRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error)
	SendFriendResponse(ctx context.Context, in *SendFriendResponseRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error)
	RemoveFriend(ctx context.Context, in *TargetRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	BlockUser(ctx context.Context, in *TargetRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UnblockUser(ctx context.Context, in *TargetRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// CreateProfile is internal: called by Auth after a successful Register to
	// seed an empty profile row. Idempotent. NOT exposed at the HTTP edge.
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type profilesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfilesServiceClient(cc grpc.ClientConnInterface) ProfilesServiceClient {
	return &profilesServiceClient{cc}
}

func (c *profilesServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, ProfilesService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) FindUserByLogin(ctx context.Context, in *FindUserByLoginRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, ProfilesService_FindUserByLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) EditUser(ctx context.Context, in *EditUserRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, ProfilesService_EditUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendFriendRequestResponse)
	err := c.cc.Invoke(ctx, ProfilesService_SendFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) SendFriendResponse(ctx context.Context, in *SendFriendResponseRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ProfilesService_SendFriendResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFriendsResponse)
	err := c.cc.Invoke(ctx, ProfilesService_ListFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) RemoveFriend(ctx context.Context, in *TargetRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ProfilesService_RemoveFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) BlockUser(ctx context.Context, in *TargetRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ProfilesService_BlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) UnblockUser(ctx context.Context, in *TargetRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ProfilesService_UnblockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ProfilesService_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfilesServiceServer is the server API for ProfilesService service.
// All implementations must embed UnimplementedProfilesServiceServer
// for forward compatibility.
//
// Profiles owns user profiles, pets, the friend graph, and blocking. It never
// returns presence itself (Map owns presence) — instead it keeps the
// `friends:{user_id}` Valkey set fresh so Map can do privacy filtering.
//
// Edge RPCs derive the acting user from the opaque session token in the
// `auth_token` header (resolved via Valkey `session:{token}`); body ids are only
// ever *target* ids. CreateProfile is internal (called by Auth over gRPC) and is
// intentionally NOT annotated for the HTTP edge.
type ProfilesServiceServer interface {
	// GetUserInfo returns the target's profile. Full shape (incl. email/phone) to
	// self or friends; reduced shape (no PII) to non-friends.
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	// FindUserByLogin looks up a user by login (case-insensitive; login is citext)
	// for stranger discovery — the frontend's "find a friend by login" search. It
	// ALWAYS returns the reduced (no-PII) shape, even when the looked-up user is
	// already a friend: a discovery endpoint must not be a PII surface, and full
	// details for real friends are available via GetUserInfo. friend_status is
	// still computed so the frontend can render the right button. If no user has
	// that login, the response carries a not-found envelope (code/message), not an
	// error.
	FindUserByLogin(context.Context, *FindUserByLoginRequest) (*GetUserInfoResponse, error)
	// EditUser updates the *acting user's own* profile (name/surname/phone/pets).
	// No user_id in the body; login/email are not editable here.
	EditUser(context.Context, *EditUserRequest) (*GetUserInfoResponse, error)
	SendFriendRequest(context.Context, *SendFriendRequestRequest) (*SendFriendRequestResponse, error)
	SendFriendResponse(context.Context, *SendFriendResponseRequest) (*StatusResponse, error)
	ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error)
	RemoveFriend(context.Context, *TargetRequest) (*StatusResponse, error)
	BlockUser(context.Context, *TargetRequest) (*StatusResponse, error)
	UnblockUser(context.Context, *TargetRequest) (*StatusResponse, error)
	// CreateProfile is internal: called by Auth after a successful Register to
	// seed an empty profile row. Idempotent. NOT exposed at the HTTP edge.
	CreateProfile(context.Context, *CreateProfileRequest) (*StatusResponse, error)
	mustEmbedUnimplementedProfilesServiceServer()
}

// UnimplementedProfilesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfilesServiceServer struct{}

func (UnimplementedProfilesServiceServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedProfilesServiceServer) FindUserByLogin(context.Context, *FindUserByLoginRequest) (*GetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUserByLogin not implemented")
}
func (UnimplementedProfilesServiceServer) EditUser(context.Context, *EditUserRequest) (*GetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditUser not implemented")
}
func (UnimplementedProfilesServiceServer) SendFriendRequest(context.Context, *SendFriendRequestRequest) (*SendFriendRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFriendRequest not implemented")
}
func (UnimplementedProfilesServiceServer) SendFriendResponse(context.Context, *SendFriendResponseRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFriendResponse not implemented")
}
func (UnimplementedProfilesServiceServer) ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFriends not implemented")
}
func (UnimplementedProfilesServiceServer) RemoveFriend(context.Context, *TargetRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFriend not implemented")
}
func (UnimplementedProfilesServiceServer) BlockUser(context.Context, *TargetRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockUser not implemented")
}
func (UnimplementedProfilesServiceServer) UnblockUser(context.Context, *TargetRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockUser not implemented")
}
func (UnimplementedProfilesServiceServer) CreateProfile(context.Context, *CreateProfileRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedProfilesServiceServer) mustEmbedUnimplementedProfilesServiceServer() {}
func (UnimplementedProfilesServiceServer) testEmbeddedByValue()                         {}

// UnsafeProfilesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfilesServiceServer will
// result in compilation errors.
type UnsafeProfilesServiceServer interface {
	mustEmbedUnimplementedProfilesServiceServer()
}

func RegisterProfilesServiceServer(s grpc.ServiceRegistrar, srv ProfilesServiceServer) {
	// If the following call panics, it indicates UnimplementedProfilesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfilesService_ServiceDesc, srv)
}

func _ProfilesService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_FindUserByLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserByLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).FindUserByLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_FindUserByLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).FindUserByLogin(ctx, req.(*FindUserByLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_EditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).EditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_EditUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).EditUser(ctx, req.(*EditUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_SendFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).SendFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_SendFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).SendFriendRequest(ctx, req.(*SendFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_SendFriendResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFriendResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).SendFriendResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_SendFriendResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).SendFriendResponse(ctx, req.(*SendFriendResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_ListFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).ListFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_ListFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).ListFriends(ctx, req.(*ListFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_RemoveFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).RemoveFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_RemoveFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).RemoveFriend(ctx, req.(*TargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_BlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).BlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_BlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).BlockUser(ctx, req.(*TargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_UnblockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).UnblockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_UnblockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).UnblockUser(ctx, req.(*TargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfilesService_ServiceDesc is the grpc.ServiceDesc for ProfilesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfilesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profiles.v1.ProfilesService",
	HandlerType: (*ProfilesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _ProfilesService_GetUserInfo_Handler,
		},
		{
			MethodName: "FindUserByLogin",
			Handler:    _ProfilesService_FindUserByLogin_Handler,
		},
		{
			MethodName: "EditUser",
			Handler:    _ProfilesService_EditUser_Handler,
		},
		{
			MethodName: "SendFriendRequest",
			Handler:    _ProfilesService_SendFriendRequest_Handler,
		},
		{
			MethodName: "SendFriendResponse",
			Handler:    _ProfilesService_SendFriendResponse_Handler,
		},
		{
			MethodName: "ListFriends",
			Handler:    _ProfilesService_ListFriends_Handler,
		},
		{
			MethodName: "RemoveFriend",
			Handler:    _ProfilesService_RemoveFriend_Handler,
		},
		{
			MethodName: "BlockUser",
			Handler:    _ProfilesService_BlockUser_Handler,
		},
		{
			MethodName: "UnblockUser",
			Handler:    _ProfilesService_UnblockUser_Handler,
		},
		{
			MethodName: "CreateProfile",
			Handler:    _ProfilesService_CreateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profiles/v1/profiles.proto",
}
