// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: profiles/v1/profiles.proto

package profilesv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FriendStatus is computed for the calling user relative to a target.
type FriendStatus int32

const (
	FriendStatus_NONE        FriendStatus = 0
	FriendStatus_PENDING_OUT FriendStatus = 1 // caller sent a request that is still pending
	FriendStatus_PENDING_IN  FriendStatus = 2 // target sent the caller a pending request
	FriendStatus_FRIENDS     FriendStatus = 3
	FriendStatus_BLOCKED     FriendStatus = 4 // caller blocked target, or target blocked caller
)

// Enum value maps for FriendStatus.
var (
	FriendStatus_name = map[int32]string{
		0: "NONE",
		1: "PENDING_OUT",
		2: "PENDING_IN",
		3: "FRIENDS",
		4: "BLOCKED",
	}
	FriendStatus_value = map[string]int32{
		"NONE":        0,
		"PENDING_OUT": 1,
		"PENDING_IN":  2,
		"FRIENDS":     3,
		"BLOCKED":     4,
	}
)

func (x FriendStatus) Enum() *FriendStatus {
	p := new(FriendStatus)
	*p = x
	return p
}

func (x FriendStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_profiles_v1_profiles_proto_enumTypes[0].Descriptor()
}

func (FriendStatus) Type() protoreflect.EnumType {
	return &file_profiles_v1_profiles_proto_enumTypes[0]
}

func (x FriendStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendStatus.Descriptor instead.
func (FriendStatus) EnumDescriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{0}
}

type Pet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Breed         string                 `protobuf:"bytes,1,opt,name=breed,proto3" json:"breed,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sex           string                 `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"` // "M" | "F"
	IsCastrated   bool                   `protobuf:"varint,4,opt,name=is_castrated,json=isCastrated,proto3" json:"is_castrated,omitempty"`
	Age           int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pet) Reset() {
	*x = Pet{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{0}
}

func (x *Pet) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *Pet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pet) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Pet) GetIsCastrated() bool {
	if x != nil {
		return x.IsCastrated
	}
	return false
}

func (x *Pet) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdTarget  string                 `protobuf:"bytes,1,opt,name=user_id_target,json=userIdTarget,proto3" json:"user_id_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoRequest) GetUserIdTarget() string {
	if x != nil {
		return x.UserIdTarget
	}
	return ""
}

// FindUserByLoginRequest carries the login to search for. Acting user comes from
// the token, never the body. Lookup is case-insensitive (login is citext).
type FindUserByLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserByLoginRequest) Reset() {
	*x = FindUserByLoginRequest{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserByLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserByLoginRequest) ProtoMessage() {}

func (x *FindUserByLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserByLoginRequest.ProtoReflect.Descriptor instead.
func (*FindUserByLoginRequest) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{2}
}

func (x *FindUserByLoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

// GetUserInfoResponse carries the full shape for self/friends and the reduced
// shape for non-friends. In the reduced shape `email` and `phone` are empty and
// `current_object_id` is omitted; `has_pii` marks which shape this is.
type GetUserInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Login           string                 `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Surname         string                 `protobuf:"bytes,6,opt,name=surname,proto3" json:"surname,omitempty"`
	Email           string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"` // full shape only
	Phone           string                 `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"` // full shape only
	Pets            []*Pet                 `protobuf:"bytes,9,rep,name=pets,proto3" json:"pets,omitempty"`
	OnWalk          bool                   `protobuf:"varint,10,opt,name=on_walk,json=onWalk,proto3" json:"on_walk,omitempty"`                             // derived by Map; Profiles reports false for MVP
	CurrentObjectId string                 `protobuf:"bytes,11,opt,name=current_object_id,json=currentObjectId,proto3" json:"current_object_id,omitempty"` // full shape only; empty when not on a walk
	FriendStatus    FriendStatus           `protobuf:"varint,12,opt,name=friend_status,json=friendStatus,proto3,enum=profiles.v1.FriendStatus" json:"friend_status,omitempty"`
	HasPii          bool                   `protobuf:"varint,13,opt,name=has_pii,json=hasPii,proto3" json:"has_pii,omitempty"` // true = full shape returned, false = reduced
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserInfoResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoResponse) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *GetUserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserInfoResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserInfoResponse) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

func (x *GetUserInfoResponse) GetOnWalk() bool {
	if x != nil {
		return x.OnWalk
	}
	return false
}

func (x *GetUserInfoResponse) GetCurrentObjectId() string {
	if x != nil {
		return x.CurrentObjectId
	}
	return ""
}

func (x *GetUserInfoResponse) GetFriendStatus() FriendStatus {
	if x != nil {
		return x.FriendStatus
	}
	return FriendStatus_NONE
}

func (x *GetUserInfoResponse) GetHasPii() bool {
	if x != nil {
		return x.HasPii
	}
	return false
}

type EditUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// No user_id: acting user comes from the token.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Phone         string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Pets          []*Pet `protobuf:"bytes,4,rep,name=pets,proto3" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditUserRequest) Reset() {
	*x = EditUserRequest{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserRequest) ProtoMessage() {}

func (x *EditUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserRequest.ProtoReflect.Descriptor instead.
func (*EditUserRequest) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{4}
}

func (x *EditUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditUserRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *EditUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *EditUserRequest) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdTarget  string                 `protobuf:"bytes,1,opt,name=user_id_target,json=userIdTarget,proto3" json:"user_id_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{5}
}

func (x *SendFriendRequestRequest) GetUserIdTarget() string {
	if x != nil {
		return x.UserIdTarget
	}
	return ""
}

type SendFriendRequestResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FriendRequestId string                 `protobuf:"bytes,3,opt,name=friend_request_id,json=friendRequestId,proto3" json:"friend_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{6}
}

func (x *SendFriendRequestResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendFriendRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendFriendRequestResponse) GetFriendRequestId() string {
	if x != nil {
		return x.FriendRequestId
	}
	return ""
}

type SendFriendResponseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FriendRequestId string                 `protobuf:"bytes,1,opt,name=friend_request_id,json=friendRequestId,proto3" json:"friend_request_id,omitempty"`
	Resolution      bool                   `protobuf:"varint,2,opt,name=resolution,proto3" json:"resolution,omitempty"` // true = accept, false = decline
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendFriendResponseRequest) Reset() {
	*x = SendFriendResponseRequest{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendResponseRequest) ProtoMessage() {}

func (x *SendFriendResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendResponseRequest.ProtoReflect.Descriptor instead.
func (*SendFriendResponseRequest) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{7}
}

func (x *SendFriendResponseRequest) GetFriendRequestId() string {
	if x != nil {
		return x.FriendRequestId
	}
	return ""
}

func (x *SendFriendResponseRequest) GetResolution() bool {
	if x != nil {
		return x.Resolution
	}
	return false
}

type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{8}
}

type Friend struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Login           string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	OnWalk          bool                   `protobuf:"varint,3,opt,name=on_walk,json=onWalk,proto3" json:"on_walk,omitempty"` // derived by Map; false for MVP in Profiles
	CurrentObjectId string                 `protobuf:"bytes,4,opt,name=current_object_id,json=currentObjectId,proto3" json:"current_object_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{9}
}

func (x *Friend) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Friend) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Friend) GetOnWalk() bool {
	if x != nil {
		return x.OnWalk
	}
	return false
}

func (x *Friend) GetCurrentObjectId() string {
	if x != nil {
		return x.CurrentObjectId
	}
	return ""
}

type IncomingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromUserId      string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	FromLogin       string                 `protobuf:"bytes,2,opt,name=from_login,json=fromLogin,proto3" json:"from_login,omitempty"`
	FriendRequestId string                 `protobuf:"bytes,3,opt,name=friend_request_id,json=friendRequestId,proto3" json:"friend_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IncomingRequest) Reset() {
	*x = IncomingRequest{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingRequest) ProtoMessage() {}

func (x *IncomingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingRequest.ProtoReflect.Descriptor instead.
func (*IncomingRequest) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{10}
}

func (x *IncomingRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *IncomingRequest) GetFromLogin() string {
	if x != nil {
		return x.FromLogin
	}
	return ""
}

func (x *IncomingRequest) GetFriendRequestId() string {
	if x != nil {
		return x.FriendRequestId
	}
	return ""
}

type OutgoingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ToUserId        string                 `protobuf:"bytes,1,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	FriendRequestId string                 `protobuf:"bytes,2,opt,name=friend_request_id,json=friendRequestId,proto3" json:"friend_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OutgoingRequest) Reset() {
	*x = OutgoingRequest{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutgoingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutgoingRequest) ProtoMessage() {}

func (x *OutgoingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutgoingRequest.ProtoReflect.Descriptor instead.
func (*OutgoingRequest) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{11}
}

func (x *OutgoingRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *OutgoingRequest) GetFriendRequestId() string {
	if x != nil {
		return x.FriendRequestId
	}
	return ""
}

type ListFriendsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Friends          []*Friend              `protobuf:"bytes,3,rep,name=friends,proto3" json:"friends,omitempty"`
	IncomingRequests []*IncomingRequest     `protobuf:"bytes,4,rep,name=incoming_requests,json=incomingRequests,proto3" json:"incoming_requests,omitempty"`
	OutgoingRequests []*OutgoingRequest     `protobuf:"bytes,5,rep,name=outgoing_requests,json=outgoingRequests,proto3" json:"outgoing_requests,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{12}
}

func (x *ListFriendsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListFriendsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListFriendsResponse) GetFriends() []*Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *ListFriendsResponse) GetIncomingRequests() []*IncomingRequest {
	if x != nil {
		return x.IncomingRequests
	}
	return nil
}

func (x *ListFriendsResponse) GetOutgoingRequests() []*OutgoingRequest {
	if x != nil {
		return x.OutgoingRequests
	}
	return nil
}

// TargetRequest is the shared shape for RemoveFriend/BlockUser/UnblockUser.
type TargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdTarget  string                 `protobuf:"bytes,1,opt,name=user_id_target,json=userIdTarget,proto3" json:"user_id_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRequest) Reset() {
	*x = TargetRequest{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRequest) ProtoMessage() {}

func (x *TargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRequest.ProtoReflect.Descriptor instead.
func (*TargetRequest) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{13}
}

func (x *TargetRequest) GetUserIdTarget() string {
	if x != nil {
		return x.UserIdTarget
	}
	return ""
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{14}
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_profiles_v1_profiles_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_v1_profiles_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_profiles_v1_profiles_proto_rawDescGZIP(), []int{15}
}

func (x *StatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_profiles_v1_profiles_proto protoreflect.FileDescriptor

const file_profiles_v1_profiles_proto_rawDesc = "" +
	"\n" +
	"\x1aprofiles/v1/profiles.proto\x12\vprofiles.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\x8e\x01\n" +
	"\x03Pet\x12\x14\n" +
	"\x05breed\x18\x01 \x01(\tR\x05breed\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\x03sex\x18\x03 \x01(\tB\v\xfaB\br\x06R\x01MR\x01FR\x03sex\x12!\n" +
	"\fis_castrated\x18\x04 \x01(\bR\visCastrated\x12\x1b\n" +
	"\x03age\x18\x05 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\x03age\"D\n" +
	"\x12GetUserInfoRequest\x12.\n" +
	"\x0euser_id_target\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\fuserIdTarget\"7\n" +
	"\x16FindUserByLoginRequest\x12\x1d\n" +
	"\x05login\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05login\"\x90\x03\n" +
	"\x13GetUserInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05login\x18\x04 \x01(\tR\x05login\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x06 \x01(\tR\asurname\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12$\n" +
	"\x04pets\x18\t \x03(\v2\x10.profiles.v1.PetR\x04pets\x12\x17\n" +
	"\aon_walk\x18\n" +
	" \x01(\bR\x06onWalk\x12*\n" +
	"\x11current_object_id\x18\v \x01(\tR\x0fcurrentObjectId\x12>\n" +
	"\rfriend_status\x18\f \x01(\x0e2\x19.profiles.v1.FriendStatusR\ffriendStatus\x12\x17\n" +
	"\ahas_pii\x18\r \x01(\bR\x06hasPii\"{\n" +
	"\x0fEditUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x02 \x01(\tR\asurname\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12$\n" +
	"\x04pets\x18\x04 \x03(\v2\x10.profiles.v1.PetR\x04pets\"J\n" +
	"\x18SendFriendRequestRequest\x12.\n" +
	"\x0euser_id_target\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\fuserIdTarget\"u\n" +
	"\x19SendFriendRequestResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x11friend_request_id\x18\x03 \x01(\tR\x0ffriendRequestId\"q\n" +
	"\x19SendFriendResponseRequest\x124\n" +
	"\x11friend_request_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x0ffriendRequestId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\bR\n" +
	"resolution\"\x14\n" +
	"\x12ListFriendsRequest\"|\n" +
	"\x06Friend\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x17\n" +
	"\aon_walk\x18\x03 \x01(\bR\x06onWalk\x12*\n" +
	"\x11current_object_id\x18\x04 \x01(\tR\x0fcurrentObjectId\"~\n" +
	"\x0fIncomingRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1d\n" +
	"\n" +
	"from_login\x18\x02 \x01(\tR\tfromLogin\x12*\n" +
	"\x11friend_request_id\x18\x03 \x01(\tR\x0ffriendRequestId\"[\n" +
	"\x0fOutgoingRequest\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x01 \x01(\tR\btoUserId\x12*\n" +
	"\x11friend_request_id\x18\x02 \x01(\tR\x0ffriendRequestId\"\x88\x02\n" +
	"\x13ListFriendsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\afriends\x18\x03 \x03(\v2\x13.profiles.v1.FriendR\afriends\x12I\n" +
	"\x11incoming_requests\x18\x04 \x03(\v2\x1c.profiles.v1.IncomingRequestR\x10incomingRequests\x12I\n" +
	"\x11outgoing_requests\x18\x05 \x03(\v2\x1c.profiles.v1.OutgoingRequestR\x10outgoingRequests\"?\n" +
	"\rTargetRequest\x12.\n" +
	"\x0euser_id_target\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\fuserIdTarget\"w\n" +
	"\x14CreateProfileRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12\x1d\n" +
	"\x05login\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05login\x12\x1d\n" +
	"\x05email\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05email\">\n" +
	"\x0eStatusResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*S\n" +
	"\fFriendStatus\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0f\n" +
	"\vPENDING_OUT\x10\x01\x12\x0e\n" +
	"\n" +
	"PENDING_IN\x10\x02\x12\v\n" +
	"\aFRIENDS\x10\x03\x12\v\n" +
	"\aBLOCKED\x10\x042\xdf\b\n" +
	"\x0fProfilesService\x12m\n" +
	"\vGetUserInfo\x12\x1f.profiles.v1.GetUserInfoRequest\x1a .profiles.v1.GetUserInfoResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/profiles/get\x12\x7f\n" +
	"\x0fFindUserByLogin\x12#.profiles.v1.FindUserByLoginRequest\x1a .profiles.v1.GetUserInfoResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/profiles/find-by-login\x12h\n" +
	"\bEditUser\x12\x1c.profiles.v1.EditUserRequest\x1a .profiles.v1.GetUserInfoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/profiles/edit\x12\x82\x01\n" +
	"\x11SendFriendRequest\x12%.profiles.v1.SendFriendRequestRequest\x1a&.profiles.v1.SendFriendRequestResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/friends/request\x12y\n" +
	"\x12SendFriendResponse\x12&.profiles.v1.SendFriendResponseRequest\x1a\x1b.profiles.v1.StatusResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/friends/respond\x12m\n" +
	"\vListFriends\x12\x1f.profiles.v1.ListFriendsRequest\x1a .profiles.v1.ListFriendsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/friends/list\x12f\n" +
	"\fRemoveFriend\x12\x1a.profiles.v1.TargetRequest\x1a\x1b.profiles.v1.StatusResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/friends/remove\x12b\n" +
	"\tBlockUser\x12\x1a.profiles.v1.TargetRequest\x1a\x1b.profiles.v1.StatusResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/friends/block\x12f\n" +
	"\vUnblockUser\x12\x1a.profiles.v1.TargetRequest\x1a\x1b.profiles.v1.StatusResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/friends/unblock\x12O\n" +
	"\rCreateProfile\x12!.profiles.v1.CreateProfileRequest\x1a\x1b.profiles.v1.StatusResponseB)Z'profiles/pkg/api/profiles/v1;profilesv1b\x06proto3"

var (
	file_profiles_v1_profiles_proto_rawDescOnce sync.Once
	file_profiles_v1_profiles_proto_rawDescData []byte
)

func file_profiles_v1_profiles_proto_rawDescGZIP() []byte {
	file_profiles_v1_profiles_proto_rawDescOnce.Do(func() {
		file_profiles_v1_profiles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profiles_v1_profiles_proto_rawDesc), len(file_profiles_v1_profiles_proto_rawDesc)))
	})
	return file_profiles_v1_profiles_proto_rawDescData
}

var file_profiles_v1_profiles_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_profiles_v1_profiles_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_profiles_v1_profiles_proto_goTypes = []any{
	(FriendStatus)(0),                 // 0: profiles.v1.FriendStatus
	(*Pet)(nil),                       // 1: profiles.v1.Pet
	(*GetUserInfoRequest)(nil),        // 2: profiles.v1.GetUserInfoRequest
	(*FindUserByLoginRequest)(nil),    // 3: profiles.v1.FindUserByLoginRequest
	(*GetUserInfoResponse)(nil),       // 4: profiles.v1.GetUserInfoResponse
	(*EditUserRequest)(nil),           // 5: profiles.v1.EditUserRequest
	(*SendFriendRequestRequest)(nil),  // 6: profiles.v1.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil), // 7: profiles.v1.SendFriendRequestResponse
	(*SendFriendResponseRequest)(nil), // 8: profiles.v1.SendFriendResponseRequest
	(*ListFriendsRequest)(nil),        // 9: profiles.v1.ListFriendsRequest
	(*Friend)(nil),                    // 10: profiles.v1.Friend
	(*IncomingRequest)(nil),           // 11: profiles.v1.IncomingRequest
	(*OutgoingRequest)(nil),           // 12: profiles.v1.OutgoingRequest
	(*ListFriendsResponse)(nil),       // 13: profiles.v1.ListFriendsResponse
	(*TargetRequest)(nil),             // 14: profiles.v1.TargetRequest
	(*CreateProfileRequest)(nil),      // 15: profiles.v1.CreateProfileRequest
	(*StatusResponse)(nil),            // 16: profiles.v1.StatusResponse
}
var file_profiles_v1_profiles_proto_depIdxs = []int32{
	1,  // 0: profiles.v1.GetUserInfoResponse.pets:type_name -> profiles.v1.Pet
	0,  // 1: profiles.v1.GetUserInfoResponse.friend_status:type_name -> profiles.v1.FriendStatus
	1,  // 2: profiles.v1.EditUserRequest.pets:type_name -> profiles.v1.Pet
	10, // 3: profiles.v1.ListFriendsResponse.friends:type_name -> profiles.v1.Friend
	11, // 4: profiles.v1.ListFriendsResponse.incoming_requests:type_name -> profiles.v1.IncomingRequest
	12, // 5: profiles.v1.ListFriendsResponse.outgoing_requests:type_name -> profiles.v1.OutgoingRequest
	2,  // 6: profiles.v1.ProfilesService.GetUserInfo:input_type -> profiles.v1.GetUserInfoRequest
	3,  // 7: profiles.v1.ProfilesService.FindUserByLogin:input_type -> profiles.v1.FindUserByLoginRequest
	5,  // 8: profiles.v1.ProfilesService.EditUser:input_type -> profiles.v1.EditUserRequest
	6,  // 9: profiles.v1.ProfilesService.SendFriendRequest:input_type -> profiles.v1.SendFriendRequestRequest
	8,  // 10: profiles.v1.ProfilesService.SendFriendResponse:input_type -> profiles.v1.SendFriendResponseRequest
	9,  // 11: profiles.v1.ProfilesService.ListFriends:input_type -> profiles.v1.ListFriendsRequest
	14, // 12: profiles.v1.ProfilesService.RemoveFriend:input_type -> profiles.v1.TargetRequest
	14, // 13: profiles.v1.ProfilesService.BlockUser:input_type -> profiles.v1.TargetRequest
	14, // 14: profiles.v1.ProfilesService.UnblockUser:input_type -> profiles.v1.TargetRequest
	15, // 15: profiles.v1.ProfilesService.CreateProfile:input_type -> profiles.v1.CreateProfileRequest
	4,  // 16: profiles.v1.ProfilesService.GetUserInfo:output_type -> profiles.v1.GetUserInfoResponse
	4,  // 17: profiles.v1.ProfilesService.FindUserByLogin:output_type -> profiles.v1.GetUserInfoResponse
	4,  // 18: profiles.v1.ProfilesService.EditUser:output_type -> profiles.v1.GetUserInfoResponse
	7,  // 19: profiles.v1.ProfilesService.SendFriendRequest:output_type -> profiles.v1.SendFriendRequestResponse
	16, // 20: profiles.v1.ProfilesService.SendFriendResponse:output_type -> profiles.v1.StatusResponse
	13, // 21: profiles.v1.ProfilesService.ListFriends:output_type -> profiles.v1.ListFriendsResponse
	16, // 22: profiles.v1.ProfilesService.RemoveFriend:output_type -> profiles.v1.StatusResponse
	16, // 23: profiles.v1.ProfilesService.BlockUser:output_type -> profiles.v1.StatusResponse
	16, // 24: profiles.v1.ProfilesService.UnblockUser:output_type -> profiles.v1.StatusResponse
	16, // 25: profiles.v1.ProfilesService.CreateProfile:output_type -> profiles.v1.StatusResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_profiles_v1_profiles_proto_init() }
func file_profiles_v1_profiles_proto_init() {
	if File_profiles_v1_profiles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profiles_v1_profiles_proto_rawDesc), len(file_profiles_v1_profiles_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profiles_v1_profiles_proto_goTypes,
		DependencyIndexes: file_profiles_v1_profiles_proto_depIdxs,
		EnumInfos:         file_profiles_v1_profiles_proto_enumTypes,
		MessageInfos:      file_profiles_v1_profiles_proto_msgTypes,
	}.Build()
	File_profiles_v1_profiles_proto = out.File
	file_profiles_v1_profiles_proto_goTypes = nil
	file_profiles_v1_profiles_proto_depIdxs = nil
}
